<html lang="ru">
<head>
    <title>Login</title>
    <link rel="stylesheet" href="${contextPath}/css/style.css">
</head>
<body>
<div class="center">
    <form method="get" class="login-form">
        <input type="email" name="login" placeholder="login">
        <input type="password" name="password" placeholder="password">
        <input type="submit">
    </form>
    <a href="${contextPath}/registration">
        <button>Регистрация</button>
    </a>
</div>
</body>
</html>